const APPROVALS_MANAGER360_TABLE_HEADERS = {
  promotion: {
    empId: "Emp ID",
    empName: "Emp Name",
    position: "Position",
    pstPromotedTo: "Position Promoted To",
    promotionDate: "Promotion Date",
    validateByCCM: "Validated By CostCenter Manger",
    validateByCCMdate: "Date",
    validateByAdmin: "Validated By HR/Admin",
    validateByAdminDate: "Date",
    status: "Status",
  },
  transfer: {
    empId: "Emp ID",
    empName: "Emp Name",
    effectiveDate: "Effective Date",
    transferType: "Typpe Of Transfer",
    status: "Status",
    action: "Action",
  },
  disciplinary: {
    empId: "Emp ID",
    empName: "Emp Name",
    costCenter: "Cost Center Name",
    showCauseDate: "Show Cause Date",
    issuedFor: "Issued For",
    dueDays: "Due Days",
    empAction: "Employee Action",
    warningIssueDaTE: "Warning Issue Date",
    PIP: "PIP",
    status: "Status",
    action: "Action",
  },
  probation: {
    empId: "Employee ID",
    costCenter: "Cost Center",
    empName: "Employee Name",
    dateOfJoining: "Date of Joining",
    dateOfConfirmation: "Date of Confirmation",
    dueDays: "Due Days",
    reminderDate: "Reminder Date",
    status: "Status",
    action: "Action",
  },
};

export default APPROVALS_MANAGER360_TABLE_HEADERS;
