const TRANSFER_TABLE_HEADERS = {
  regular: {
    sno: "S.NO",
    empId: "EMP ID",
    empName: "EMP NAME",
    curDept: "CURRENT DEPARTMENT",
    curPos: "CURRENT POSITION",
    curCostCent: "CURRENT COST CENTRE",
    curManager: "CURRENT MANAGER",
    curLocation: "CURRENT LOCATION",
    newDept: "NEW DEPARTMENT",
    newPos: "NEW POSITION",
    newCostCent: "NEW COST CENTRE",
    newManager: "NEW MANAGER",
    newLocation: "NEW LOCATION",
    status: "STATUS",
  },
  entity: {
    sno: "S.NO",
    empId: "OLD EMP ID",
    empName: "EMP NAME",
    oldEntity: "OLD ENTITY",
    newEmpId: "NEW EMP ID",
    newEntity: "NEW ENTITY",
    newManager: "NEW MANAGER",
    effectiveDate: "EFFECTIVE DATE",
    status: "STATUS",
    alert: "VIEW SIGNED DOCUMENT",
  },
  international: {
    sno: "S.NO",
    empId: "EMP ID",
    empName: "EMP NAME",
    oldCountry: "OLD COUNTRY",
    oldDesignation: "OLD DESIGNATION",
    newCountry: "NEW COUNTRY",
    newDesignation: "NEW DESIGNATION",
    effDate: "EFFECTIVE DATE",
    dateOfReturn: "DATE OF RETURN",
    termOfProject: "TERM OF PROJECT",
    contractStatus: "CONTRACT STATUS",
    status: "STATUS",
  },
  employment: {
    sno: "S.NO",
    empId: "EMP ID",
    empName: "EMP NAME",
    oldEmpContractType: "OLD EMPLOYMENT CONTRACT TYPE",
    newEmpContractType: "NEW EMPLOYMENT CONTRACT TYPE",
    effectiveDate: "EFFECTIVE DATE",
    status: "STATUS",
    alert: "VIEW SIGNED DOCUMENT",

    // curDept: "Current Department",
    // curPos: "Current Position",
    // curCostCent: "Current Cost Centre",
    // curManager: "Current Manager",
    // curLocation: "Current Location",
    // newDept: "New Department",
    // newPos: "New Position",
    // newCostCent: "New Cost Centre",
    // newManager: "NEW MANAGER",
    // newLocation: "New Location",
  },
};

export default TRANSFER_TABLE_HEADERS;
