const BANK_NAMES = [
  "Almora Urban Co-operative Bank Ltd",
  "ANZ Bank",
  "Apna Sahakari Bank Ltd",
  "Axis Bank",
  "Bank of America N.A.",
  "Bank of Baroda",
  "Bank of India",
  "Bank of Maharashtra",
  "Bankura DCCB",
  "Barclays Bank PLC",
  "Canara Bank",
  "Capital Local Area Bank Ltd",
  "Catholic Syrian Bank",
  "Central Bank of India",
  "Citibank",
  "Corporation Bank",
  "Credit Agricole Corporate And Investment Bank",
  "Credit Suisse AG",
  "Dakhin Dinajpur DCCB",
  "Darjeeling DCCB",
  "Development Credit Bank",
  "Dhanlaxmi Bank Ltd",
  "Dombivli Nagari Sahakari Bank Ltd",
  "HDFC Bank",
  "Howrah DCCB",
  "HSBC Bank",
  "ICICI Bank",
  "Indian Bank",
  "ING Vyasya Bank",
  "Indian Overseas Bank",
  "Jalgaon Janata Sahakari Bank Ltd",
  "Jalpaiguri DCCB",
  "Kallappanna Awade Ichalkaranji Janata Sah Bank Ltd",
  "Karnataka Bank",
  "Karur Vysya Bank",
  "Kotak Bank",
  "Lakshmi Vilas Bank",
  "Malda DCCB",
  "Mehsana Urban Co-op Bank Ltd",
  "Mizuho Corporate Bank Ltd",
  "Mugberia CCB",
  "Murshidabad DCCB",
  "Nadia DCCB",
  "Nagpur Nagrik Sahakari Bank Ltd",
  "NKGSB Co-op Bank Ltd",
  "Pragathi Krishna Gramin Bank",
  "Punjab & Sind Bank",
  "Punjab National Bank",
  "Purulia DCCB",
  "Raiganj DCCB",
  "Rajkot Nagarik Sahakari Bank Ltd",
  "Standard Chartered Bank",
  "State Bank of India",
  "Shreyas Gramin Bank",
  "Societe Generale",
  "South Indian Bank",
  "South Malabar Gramin Bank",
  "Tamilnad Mercantile Bank Ltd",
  "Tamluk Ghatal CCB",
  "The Ahmedabad Mercantile Bank Ltd",
  "The Bank of Tokyo-Mitsubishi UFJ Ltd",
  "The Bharat Co-operative Bank (Mumbai) Ltd",
  "The Cosmos Co-Op Bank Ltd",
  "The Federal Bank Ltd",
  "The Karad Urban Co-Op Bank Ltd",
  "The Saraswat Co-operative Bank Ltd",
  "The Shamrao Vithal Co-operative Bank Ltd",
  "The Tamilnadu State Apex Co-op Bank",
  "The West Bengal State Co operative Bank",
  "TJ Sahakari Bank Ltd",
  "UBS AG",
  "UCO Bank",
  "Union Bank of India",
  "United Bank of India",
  "Vidyasagar CCB",
  "Yes Bank",
  "IDBI Bank",
  "RBS (Royal Bank of Scotland)",
];

export default BANK_NAMES;
