//CUSTOMIZER 
export const ADD_COSTOMIZER = "ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS = "ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIXlAYOUT = "ADD_MIXlAYOUT";
export const CREATE_SHIFT = "CREATE_SHIFT";

// LOGIN
export const SET_ACCESS_TOKEN_SUCCESS = 'SET_ACCESS_TOKEN_SUCCESS';
export const SET_ACCESS_TOKEN_FAIL = 'SET_ACCESS_TOKEN_FAIL';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';