//CUSTOMIZER 
export const ADD_COSTOMIZER = "ADD_COSTOMIZER";
export const ADD_LAYOUT = "ADD_LAYOUT";
export const ADD_SIDEBAR_TYPES = "ADD_SIDEBAR_TYPES";
export const ADD_SIDEBAR_SETTINGS = "ADD_SIDEBAR_SETTINGS";
export const ADD_COLOR = "ADD_COLOR";
export const ADD_MIXlAYOUT = "ADD_MIXlAYOUT";
export const CREATE_SHIFT = "CREATE_SHIFT";

// LOGIN
export const SET_ACCESS_TOKEN_SUCCESS = 'SET_ACCESS_TOKEN_SUCCESS';
export const SET_ACCESS_TOKEN_FAIL = 'SET_ACCESS_TOKEN_FAIL';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';

//sUPPORT Module
export const VIEW_TICKET_LISTING = 'VIEW_TICKET_LISTING'
export const COMPLETE_STATUS = 'COMPLETE_STATUS'
export const TICKET_STATUS = 'TICKET_STATUS'
export const VIEW_TICKET_ID_INFO = 'VIEW_TICKET_ID_INFO'
export const UPDATE_TICKET = 'UPDATE_TICKET'

//Group Module
export const GROUP_SERVICE_VIEW = 'GROUP_SERVICE_VIEW'
export const  CREATE_SERVICE_ROLE = 'CREATE_SERVICE_ROLE'