const TRANSFER_TABLE_HEADERS = {
  regular: {
    sno: "SNo",
    empId: "Emp ID",
    empName: "Emp Name",
    curDept: "Current Department",
    curPos: "Current Position",
    curCostCent: "Current Cost Centre",
    curManager: "Current Manager",
    curLocation: "Current Location",
    newDept: "New Department",
    newPos: "New Position",
    newCostCent: "New Cost Centre",
    newManager: "New Manager",
    newLocation: "New Location",
    status: "Status",
    action: "Edit/View",
  },
  entity: {
    sno: "SNo",
    empId: "Emp ID",
    empName: "Emp Name",
    curDept: "Current Department",
    curPos: "Current Position",
    curCostCent: "Current Cost Centre",
    curManager: "Current Manager",
    curLocation: "Current Location",
    newDept: "New Department",
    newPos: "New Position",
    newCostCent: "New Cost Centre",
    newManager: "New Manager",
    newLocation: "New Location",
    status: "Status",
    action: "Edit/View",
  },
  international: {
    sno: "SNo",
    empId: "Emp ID",
    empName: "Emp Name",
    curDept: "Current Department",
    curPos: "Current Position",
    curCostCent: "Current Cost Centre",
    curManager: "Current Manager",
    curLocation: "Current Location",
    newDept: "New Department",
    newPos: "New Position",
    newCostCent: "New Cost Centre",
    newManager: "New Manager",
    newLocation: "New Location",
    status: "Status",
    action: "Edit/View",
  },
  employment: {
    sno: "SNo",
    empId: "Emp ID",
    empName: "Emp Name",
    curDept: "Current Department",
    curPos: "Current Position",
    curCostCent: "Current Cost Centre",
    curManager: "Current Manager",
    curLocation: "Current Location",
    newDept: "New Department",
    newPos: "New Position",
    newCostCent: "New Cost Centre",
    newManager: "New Manager",
    newLocation: "New Location",
    status: "Status",
    action: "Edit/View",
  },
};

export default TRANSFER_TABLE_HEADERS;
