const TRANSFER_TABLE_HEADERS = {
  regular: {
    sno: "S.No",
    empId: "Emp ID",
    empName: "Emp Name",
    curDept: "Current Department",
    curPos: "Current Position",
    curCostCent: "Current Cost Centre",
    curManager: "Current Manager",
    curLocation: "Current Location",
    newDept: "New Department",
    newPos: "New Position",
    newCostCent: "New Cost Centre",
    newManager: "New Manager",
    newLocation: "New Location",
    status: "Status",
    view: "View",
    action: "Action",
  },
  entity: {
    sno: "S.No",
    empId: "Old Emp ID",
    empName: "Emp Name",
    oldEntity: "Old Entity",
    newEmpId: "New Emp ID",
    newEntity: "New Entity",
    newManager: "New Manager",
    effectiveDate: "Effective Date",
    status: "Status",
    view: "View",
    action: "Action",
    alert: "View Signed Document",
  },
  international: {
    sno: "S.No",
    empId: "Emp ID",
    empName: "Emp Name",
    oldCountry: "Old Country",
    oldDesignation: "Old Designation",
    newCountry: "New Country",
    newDesignation: "New Designation",
    effDate: "Effective Date",
    dateOfReturn: "Date Of Return",
    termOfProject: "Term Of Project",
    contractStatus: "Contract Status",
    status: "Status",
    view: "View",
    action: "Action",
  },
  employment: {
    sno: "S.No",
    empId: "Emp ID",
    empName: "Emp Name",
    oldEmpContractType: "Old Employment Contract Type",
    newEmpContractType: "New Employment Contract Type",
    effectiveDate: "Effective Date",
    status: "Status",
    view: "View",
    action: "Action",
    alert: "View Signed Document",

    // curDept: "Current Department",
    // curPos: "Current Position",
    // curCostCent: "Current Cost Centre",
    // curManager: "Current Manager",
    // curLocation: "Current Location",
    // newDept: "New Department",
    // newPos: "New Position",
    // newCostCent: "New Cost Centre",
    // newManager: "New Manager",
    // newLocation: "New Location",
  },
};

export default TRANSFER_TABLE_HEADERS;
